repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [
          --line-length, '79',
          --include, '\.pyi?$',
          --skip-string-normalization
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [
          --line-length, '79',
          --use-parentheses,
          --trailing-comma,
          --multi-line, '3'
        ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          --max-line-length, '79',
          --max-complexity, '10'
        ]
